services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    container_name: web
    volumes:
      - ./web:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    env_file:
      - ./web/.env.development

volumes:
  node_modules: