services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile.prod
    container_name: web
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - ./web/.env.production

volumes:
  node_modules: