services:
  web:
    build:
      context: .
      dockerfile: packages/web/Dockerfile.dev
    container_name: web
    volumes:
      - ./packages/web:/app/packages/web
      - /app/packages/web/node_modules
      - /app/packages/web/.next
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    env_file:
      - ./packages/web/.env.development

volumes:
  node_modules: